In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Data/df_processed.csv')
df.head()

Unnamed: 0  LBXTC  RIAGENDR  RIDRETH3  RIDAGEYR  BMXWT  BMXHT  BMXBMI  \
0           1  265.0       1.0       3.0      53.0   90.4  171.4    30.8   
1           2  229.0       1.0       3.0      78.0   83.4  170.1    28.8   
2           4  204.0       2.0       4.0      42.0   55.2  164.9    20.3   
3           5  190.0       2.0       1.0      72.0   64.4  150.0    28.6   
4           7  164.0       1.0       4.0      22.0   76.6  165.4    28.0   

   BPXPLS  BPXPULS  ...  PAD615  PAQ625  PAD630  PAQ655  PAD660  PAQ670  \
0    72.0      1.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1    56.0      1.0  ...     0.0     4.0   240.0     0.0     0.0     0.0   
2    76.0      1.0  ...     0.0     7.0   480.0     0.0     0.0     0.0   
3    64.0      1.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4    66.0      1.0  ...     0.0     0.0     0.0     2.0    60.0     0.0   

   PAD675  KIQ022    Systolic  Diastolic  
0     0.0     NaN  140.000000  86.000000  
1     0.0     NaN  135.333333  45.333333  
2     0.0     NaN  104.000000  60.000000  
3     0.0     NaN  119.333333  58.666667  
4     0.0     NaN  111.333333  72.666667  

[5 rows x 47 columns]

In [3]:
df.columns

Index(['Unnamed: 0', 'LBXTC', 'RIAGENDR', 'RIDRETH3', 'RIDAGEYR', 'BMXWT',
       'BMXHT', 'BMXBMI', 'BPXPLS', 'BPXPULS', 'DR1TKCAL', 'DR1TPROT',
       'DR1TCARB', 'DR1TSUGR', 'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT', 'DR1TMFAT',
       'DR1TPFAT', 'DR1TCHOL', 'DR1TSODI', 'DR1TVD', 'DR1TCALC', 'DR1TIRON',
       'DR1TPOTA', 'DR1_300', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'BPQ020',
       'BPQ050A', 'BPQ080', 'BPQ100D', 'DIQ010', 'MCQ170M', 'SMQ681', 'PAQ610',
       'PAD615', 'PAQ625', 'PAD630', 'PAQ655', 'PAD660', 'PAQ670', 'PAD675',
       'KIQ022', 'Systolic', 'Diastolic'],
      dtype='object')

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
null_rows = (100*df.isnull().sum(axis=1)/df.shape[1]).sort_values(ascending=False)
null_rows[null_rows > 25].index

Int64Index([ 743,  535,  895,   37,  379,  141,  982, 2092,   65, 1248,
            ...
            4840, 4257, 3265, 4727, 4692, 2581, 4524, 3044, 3206, 1230],
           dtype='int64', length=345)

In [6]:
df.drop(null_rows[null_rows>25].index,axis=0,inplace=True)

In [7]:
null_cols = (100*df.isnull().sum(axis=0)/df.shape[0]).sort_values(ascending=False)
null_cols[null_cols>25]

KIQ022    49.098325
dtype: float64

As the variable regarding Kidney conditions is the only variable with more than a quarter of the data missing, that will be dropped.

note to self - go back through the docs and see if the result of a prior question skips over this

In [8]:
df.drop('KIQ022',axis=1,inplace=True)

## Looking for erroneous data

In [9]:
df.columns

Index(['LBXTC', 'RIAGENDR', 'RIDRETH3', 'RIDAGEYR', 'BMXWT', 'BMXHT', 'BMXBMI',
       'BPXPLS', 'BPXPULS', 'DR1TKCAL', 'DR1TPROT', 'DR1TCARB', 'DR1TSUGR',
       'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT', 'DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL',
       'DR1TSODI', 'DR1TVD', 'DR1TCALC', 'DR1TIRON', 'DR1TPOTA', 'DR1_300',
       'ALQ120Q', 'ALQ120U', 'ALQ130', 'BPQ020', 'BPQ050A', 'BPQ080',
       'BPQ100D', 'DIQ010', 'MCQ170M', 'SMQ681', 'PAQ610', 'PAD615', 'PAQ625',
       'PAD630', 'PAQ655', 'PAD660', 'PAQ670', 'PAD675', 'Systolic',
       'Diastolic'],
      dtype='object')

In [12]:
df.LBXTC.describe()

count    4658.000000
mean      189.365608
std        41.900601
min        69.000000
25%       160.000000
50%       186.000000
75%       213.000000
max       612.000000
Name: LBXTC, dtype: float64

Although the max is large, there doesn't appear to be an errors.  I'll have to figure out what I want to do with outliers.

In [13]:
df.RIAGENDR.unique()

array([1., 2.])

In [14]:
df.RIDRETH3.unique()

array([3., 4., 1., 7., 2., 6.])

In [15]:
df.RIDAGEYR.describe()

count    4658.000000
mean       49.384714
std        17.424684
min        20.000000
25%        34.250000
50%        49.000000
75%        63.000000
max        80.000000
Name: RIDAGEYR, dtype: float64

In [16]:
df.BMXWT.describe()

count    4635.000000
mean       82.320820
std        22.088128
min        32.300000
25%        66.800000
50%        78.900000
75%        93.850000
max       198.900000
Name: BMXWT, dtype: float64

In [17]:
df.BMXHT.describe()

count    4633.000000
mean      167.099426
std         9.986096
min       137.600000
25%       159.800000
50%       166.800000
75%       174.300000
max       202.700000
Name: BMXHT, dtype: float64

In [18]:
df.BMXBMI.describe()

count    4627.000000
mean       29.398617
std         7.164954
min        14.500000
25%        24.300000
50%        28.200000
75%        33.000000
max        70.100000
Name: BMXBMI, dtype: float64

In [19]:
df.BPXPLS.describe()

count    4581.000000
mean       71.765990
std        11.594054
min        36.000000
25%        64.000000
50%        70.000000
75%        78.000000
max       160.000000
Name: BPXPLS, dtype: float64

In [20]:
df.BPXPULS.unique()

array([ 1.,  2., nan])

In [21]:
df.DR1TKCAL.describe()

count     4658.000000
mean      2091.592744
std        986.841250
min        117.000000
25%       1435.000000
50%       1935.500000
75%       2555.750000
max      12108.000000
Name: DR1TKCAL, dtype: float64

In [22]:
df.DR1TPROT.describe()

count    4.658000e+03
mean     8.192210e+01
std      4.403831e+01
min      5.397605e-79
25%      5.233250e+01
50%      7.386500e+01
75%      1.013775e+02
max      5.131000e+02
Name: DR1TPROT, dtype: float64

For protein amount, a value of 5.397e-79 seems to be a mistake.  I'm replacing all values less than 1 with 0

In [24]:
df.loc[df.DR1TPROT<1,'DR1TPROT']=0
df.DR1TPROT.describe()

count    4658.000000
mean       81.922102
std        44.038307
min         0.000000
25%        52.332500
50%        73.865000
75%       101.377500
max       513.100000
Name: DR1TPROT, dtype: float64

In [25]:
df.DR1TCARB.describe()

count    4658.000000
mean      247.133828
std       123.387580
min         8.670000
25%       162.582500
50%       227.485000
75%       308.275000
max      1423.870000
Name: DR1TCARB, dtype: float64

In [26]:
df.DR1TSUGR.describe()

count    4658.000000
mean      105.321627
std        74.766506
min         0.130000
25%        55.112500
50%        90.615000
75%       138.465000
max      1115.500000
Name: DR1TSUGR, dtype: float64

In [27]:
df.DR1TFIBE.describe()

count    4.658000e+03
mean     1.687106e+01
std      1.082425e+01
min      5.397605e-79
25%      9.500000e+00
50%      1.450000e+01
75%      2.160000e+01
max      1.363000e+02
Name: DR1TFIBE, dtype: float64

Again, extremely small min values

In [28]:
sum(df.DR1TFIBE<1)

17

This time there appears to be more small values, taking a look at these

In [29]:
df[df.DR1TFIBE<1]['DR1TFIBE']

261     3.000000e-01
359     7.000000e-01
737     4.000000e-01
835     7.000000e-01
963     5.397605e-79
1406    1.000000e-01
1952    4.000000e-01
2483    8.000000e-01
2490    5.000000e-01
2890    5.397605e-79
3168    2.000000e-01
3316    4.000000e-01
3584    8.000000e-01
3724    5.397605e-79
3979    5.397605e-79
4053    3.000000e-01
4853    4.000000e-01
Name: DR1TFIBE, dtype: float64

Values of 0.2 may be reasonable, but anything less than 0.01 is probably an error.

In [30]:
df[df.DR1TFIBE<0.05]['DR1TFIBE']

963     5.397605e-79
2890    5.397605e-79
3724    5.397605e-79
3979    5.397605e-79
Name: DR1TFIBE, dtype: float64

In [31]:
df.loc[df.DR1TFIBE<0.05,'DR1TFIBE']=0

In [32]:
df.DR1TFIBE.describe()

count    4658.000000
mean       16.871061
std        10.824250
min         0.000000
25%         9.500000
50%        14.500000
75%        21.600000
max       136.300000
Name: DR1TFIBE, dtype: float64

In [ ]:
df