In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../Data/df_processed.csv')
df.head()

Unnamed: 0  LBXTC  RIAGENDR  RIDRETH3  RIDAGEYR  BMXWT  BMXHT  BMXBMI  \
0           1  265.0       1.0       3.0      53.0   90.4  171.4    30.8   
1           2  229.0       1.0       3.0      78.0   83.4  170.1    28.8   
2           4  204.0       2.0       4.0      42.0   55.2  164.9    20.3   
3           5  190.0       2.0       1.0      72.0   64.4  150.0    28.6   
4           7  164.0       1.0       4.0      22.0   76.6  165.4    28.0   

   BPXPLS  BPXPULS  ...  PAD615  PAQ625  PAD630  PAQ655  PAD660  PAQ670  \
0    72.0      1.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1    56.0      1.0  ...     0.0     4.0   240.0     0.0     0.0     0.0   
2    76.0      1.0  ...     0.0     7.0   480.0     0.0     0.0     0.0   
3    64.0      1.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4    66.0      1.0  ...     0.0     0.0     0.0     2.0    60.0     0.0   

   PAD675  KIQ022    Systolic  Diastolic  
0     0.0     NaN  140.000000  86.000000  
1     0.0     NaN  135.333333  45.333333  
2     0.0     NaN  104.000000  60.000000  
3     0.0     NaN  119.333333  58.666667  
4     0.0     NaN  111.333333  72.666667  

[5 rows x 47 columns]

In [3]:
df.columns

Index(['Unnamed: 0', 'LBXTC', 'RIAGENDR', 'RIDRETH3', 'RIDAGEYR', 'BMXWT',
       'BMXHT', 'BMXBMI', 'BPXPLS', 'BPXPULS', 'DR1TKCAL', 'DR1TPROT',
       'DR1TCARB', 'DR1TSUGR', 'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT', 'DR1TMFAT',
       'DR1TPFAT', 'DR1TCHOL', 'DR1TSODI', 'DR1TVD', 'DR1TCALC', 'DR1TIRON',
       'DR1TPOTA', 'DR1_300', 'ALQ120Q', 'ALQ120U', 'ALQ130', 'BPQ020',
       'BPQ050A', 'BPQ080', 'BPQ100D', 'DIQ010', 'MCQ170M', 'SMQ681', 'PAQ610',
       'PAD615', 'PAQ625', 'PAD630', 'PAQ655', 'PAD660', 'PAQ670', 'PAD675',
       'KIQ022', 'Systolic', 'Diastolic'],
      dtype='object')

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
null_rows = (100*df.isnull().sum(axis=1)/df.shape[1]).sort_values(ascending=False)
null_rows[null_rows > 25].index

Int64Index([ 743,  535,  895,   37,  379,  141,  982, 2092,   65, 1248,
            ...
            4840, 4257, 3265, 4727, 4692, 2581, 4524, 3044, 3206, 1230],
           dtype='int64', length=345)

In [6]:
df.drop(null_rows[null_rows>25].index,axis=0,inplace=True)

In [7]:
null_cols = (100*df.isnull().sum(axis=0)/df.shape[0]).sort_values(ascending=False)
null_cols[null_cols>25]

KIQ022    49.098325
dtype: float64

As the variable regarding Kidney conditions is the only variable with more than a quarter of the data missing, that will be dropped.

note to self - go back through the docs and see if the result of a prior question skips over this

In [8]:
df.drop('KIQ022',axis=1,inplace=True)

## Looking for erroneous data

In [9]:
df.columns

Index(['LBXTC', 'RIAGENDR', 'RIDRETH3', 'RIDAGEYR', 'BMXWT', 'BMXHT', 'BMXBMI',
       'BPXPLS', 'BPXPULS', 'DR1TKCAL', 'DR1TPROT', 'DR1TCARB', 'DR1TSUGR',
       'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT', 'DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL',
       'DR1TSODI', 'DR1TVD', 'DR1TCALC', 'DR1TIRON', 'DR1TPOTA', 'DR1_300',
       'ALQ120Q', 'ALQ120U', 'ALQ130', 'BPQ020', 'BPQ050A', 'BPQ080',
       'BPQ100D', 'DIQ010', 'MCQ170M', 'SMQ681', 'PAQ610', 'PAD615', 'PAQ625',
       'PAD630', 'PAQ655', 'PAD660', 'PAQ670', 'PAD675', 'Systolic',
       'Diastolic'],
      dtype='object')

In [10]:
df.LBXTC.describe()

count    4658.000000
mean      189.365608
std        41.900601
min        69.000000
25%       160.000000
50%       186.000000
75%       213.000000
max       612.000000
Name: LBXTC, dtype: float64

Although the max is large, there doesn't appear to be an errors.  I'll have to figure out what I want to do with outliers.

In [11]:
df.RIAGENDR.unique()

array([1., 2.])

In [12]:
df.RIDRETH3.unique()

array([3., 4., 1., 7., 2., 6.])

In [13]:
df.RIDAGEYR.describe()

count    4658.000000
mean       49.384714
std        17.424684
min        20.000000
25%        34.250000
50%        49.000000
75%        63.000000
max        80.000000
Name: RIDAGEYR, dtype: float64

In [14]:
df.BMXWT.describe()

count    4635.000000
mean       82.320820
std        22.088128
min        32.300000
25%        66.800000
50%        78.900000
75%        93.850000
max       198.900000
Name: BMXWT, dtype: float64

In [15]:
df.BMXHT.describe()

count    4633.000000
mean      167.099426
std         9.986096
min       137.600000
25%       159.800000
50%       166.800000
75%       174.300000
max       202.700000
Name: BMXHT, dtype: float64

In [16]:
df.BMXBMI.describe()

count    4627.000000
mean       29.398617
std         7.164954
min        14.500000
25%        24.300000
50%        28.200000
75%        33.000000
max        70.100000
Name: BMXBMI, dtype: float64

In [17]:
df.BPXPLS.describe()

count    4581.000000
mean       71.765990
std        11.594054
min        36.000000
25%        64.000000
50%        70.000000
75%        78.000000
max       160.000000
Name: BPXPLS, dtype: float64

In [18]:
df.BPXPULS.unique()

array([ 1.,  2., nan])

In [19]:
df.DR1TKCAL.describe()

count     4658.000000
mean      2091.592744
std        986.841250
min        117.000000
25%       1435.000000
50%       1935.500000
75%       2555.750000
max      12108.000000
Name: DR1TKCAL, dtype: float64

In [20]:
df.DR1TPROT.describe()

count    4.658000e+03
mean     8.192210e+01
std      4.403831e+01
min      5.397605e-79
25%      5.233250e+01
50%      7.386500e+01
75%      1.013775e+02
max      5.131000e+02
Name: DR1TPROT, dtype: float64

For protein amount, a value of 5.397e-79 seems to be a mistake.  I'm replacing all values less than 1 with 0

In [21]:
df.loc[df.DR1TPROT<1,'DR1TPROT']=0
df.DR1TPROT.describe()

count    4658.000000
mean       81.922102
std        44.038307
min         0.000000
25%        52.332500
50%        73.865000
75%       101.377500
max       513.100000
Name: DR1TPROT, dtype: float64

In [22]:
df.DR1TCARB.describe()

count    4658.000000
mean      247.133828
std       123.387580
min         8.670000
25%       162.582500
50%       227.485000
75%       308.275000
max      1423.870000
Name: DR1TCARB, dtype: float64

In [23]:
df.DR1TSUGR.describe()

count    4658.000000
mean      105.321627
std        74.766506
min         0.130000
25%        55.112500
50%        90.615000
75%       138.465000
max      1115.500000
Name: DR1TSUGR, dtype: float64

In [24]:
df.DR1TFIBE.describe()

count    4.658000e+03
mean     1.687106e+01
std      1.082425e+01
min      5.397605e-79
25%      9.500000e+00
50%      1.450000e+01
75%      2.160000e+01
max      1.363000e+02
Name: DR1TFIBE, dtype: float64

Again, extremely small min values

In [25]:
sum(df.DR1TFIBE<1)

17

This time there appears to be more small values, taking a look at these

In [26]:
df[df.DR1TFIBE<1]['DR1TFIBE']

261     3.000000e-01
359     7.000000e-01
737     4.000000e-01
835     7.000000e-01
963     5.397605e-79
1406    1.000000e-01
1952    4.000000e-01
2483    8.000000e-01
2490    5.000000e-01
2890    5.397605e-79
3168    2.000000e-01
3316    4.000000e-01
3584    8.000000e-01
3724    5.397605e-79
3979    5.397605e-79
4053    3.000000e-01
4853    4.000000e-01
Name: DR1TFIBE, dtype: float64

Values of 0.2 may be reasonable, but anything less than 0.01 is probably an error.

In [27]:
df[df.DR1TFIBE<0.05]['DR1TFIBE']

963     5.397605e-79
2890    5.397605e-79
3724    5.397605e-79
3979    5.397605e-79
Name: DR1TFIBE, dtype: float64

In [28]:
df.loc[df.DR1TFIBE<0.05,'DR1TFIBE']=0

In [29]:
df.DR1TFIBE.describe()

count    4658.000000
mean       16.871061
std        10.824250
min         0.000000
25%         9.500000
50%        14.500000
75%        21.600000
max       136.300000
Name: DR1TFIBE, dtype: float64

In [30]:
df.DR1TTFAT.describe()

count    4.658000e+03
mean     8.172349e+01
std      4.746392e+01
min      5.397605e-79
25%      4.997000e+01
50%      7.378500e+01
75%      1.030075e+02
max      5.483800e+02
Name: DR1TTFAT, dtype: float64

Again very small values that may be errors

In [31]:
df[df.DR1TTFAT<0.1]['DR1TTFAT']

3979    5.397605e-79
Name: DR1TTFAT, dtype: float64

In [32]:
df.loc[df.DR1TTFAT<0.1,'DR1TTFAT']=0
df.DR1TTFAT.describe()

count    4658.000000
mean       81.723486
std        47.463920
min         0.000000
25%        49.970000
50%        73.785000
75%       103.007500
max       548.380000
Name: DR1TTFAT, dtype: float64

In [33]:
df.DR1TSFAT.describe()

count    4.658000e+03
mean     2.621632e+01
std      1.654159e+01
min      5.397605e-79
25%      1.497900e+01
50%      2.292800e+01
75%      3.379300e+01
max      1.774670e+02
Name: DR1TSFAT, dtype: float64

For the rest of the nutrient information, I'm going to go through the values and anything less than 0.01 I'm replacing with 0

In [34]:
for x in ['DR1TSFAT','DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL','DR1TSODI', 'DR1TVD', 'DR1TCALC', 'DR1TIRON', 'DR1TPOTA']:
    df.loc[df[x]<0.01,x]=0

In [35]:
df.DR1TSFAT.describe()

count    4658.000000
mean       26.216316
std        16.541587
min         0.000000
25%        14.979000
50%        22.928000
75%        33.793000
max       177.467000
Name: DR1TSFAT, dtype: float64

In [36]:
df.DR1TMFAT.describe()

count    4658.000000
mean       28.809978
std        17.783049
min         0.000000
25%        16.993000
50%        25.572000
75%        36.558000
max       221.673000
Name: DR1TMFAT, dtype: float64

In [37]:
df.DR1TPFAT.describe()

count    4658.000000
mean       19.096201
std        13.221963
min         0.000000
25%        10.207000
50%        16.409000
75%        24.555250
max       182.462000
Name: DR1TPFAT, dtype: float64

In [38]:
df.DR1TCHOL.describe()

count    4658.000000
mean      300.318592
std       239.314287
min         0.000000
25%       134.000000
50%       232.500000
75%       408.000000
max      2352.000000
Name: DR1TCHOL, dtype: float64

In [39]:
df.DR1TSODI.describe()

count     4658.000000
mean      3504.799699
std       1846.270129
min         29.000000
25%       2249.250000
50%       3175.500000
75%       4354.000000
max      21399.000000
Name: DR1TSODI, dtype: float64

In [40]:
df.DR1TVD.describe()

count    4658.000000
mean        4.512774
std         6.117031
min         0.000000
25%         1.000000
50%         2.800000
75%         5.700000
max        78.100000
Name: DR1TVD, dtype: float64

In [41]:
df.DR1TCALC.describe()

count    4658.000000
mean      905.994418
std       583.691597
min        18.000000
25%       502.250000
50%       787.000000
75%      1152.000000
max      7337.000000
Name: DR1TCALC, dtype: float64

In [42]:
df.DR1TIRON.describe()

count    4658.000000
mean       13.845676
std         8.008605
min         0.050000
25%         8.400000
50%        12.140000
75%        17.617500
max        89.550000
Name: DR1TIRON, dtype: float64

In [43]:
df.DR1TPOTA.describe()

count     4658.000000
mean      2554.786818
std       1217.403526
min         68.000000
25%       1695.250000
50%       2384.000000
75%       3218.750000
max      14072.000000
Name: DR1TPOTA, dtype: float64

In [44]:
df.DR1_300.unique()
# I do need to adjust for those with values of 9, don't know

array([2., 1., 3., 9.])

In [45]:
df.loc[df.DR1_300==9,'DR1_300']=np.nan

In [46]:
df.ALQ120Q.describe()

count    4.456000e+03
mean     2.847172e+00
std      1.246271e+01
min      0.000000e+00
25%      5.397605e-79
50%      1.000000e+00
75%      3.000000e+00
max      3.650000e+02
Name: ALQ120Q, dtype: float64

Again there are many with very small values, replacing them with 0s

In [47]:
df.loc[df.ALQ120Q<0.01,'ALQ120Q']=0
df.ALQ120Q.describe()

count    4456.000000
mean        2.847172
std        12.462711
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max       365.000000
Name: ALQ120Q, dtype: float64

In [48]:
df.ALQ120U.unique()

array([ 1., nan,  3.,  2.])

In [49]:
df.ALQ130.describe()

count    3700.00000
mean        2.20000
std         2.40943
min         0.00000
25%         1.00000
50%         2.00000
75%         3.00000
max        25.00000
Name: ALQ130, dtype: float64

Since the min is 0, checking to see if there are any less than 0.01 but greater than 0...

In [50]:
df[(df.ALQ130>0)&(df.ALQ130<0.01)].shape

(0, 45)

Apparently not

In [51]:
df.BPQ020.unique()

array([ 2.,  1., nan])

In [52]:
df.BPQ050A.unique()

array([ 2.,  1., nan,  9.])

In [53]:
# I thought I took care of this, need to look at my code
df.loc[df.BPQ050A==9,'BPQ050A']=np.nan
# ok, from my code I did not change this, will need to fix that later.

In [54]:
df.columns[-20:]

Index(['ALQ120Q', 'ALQ120U', 'ALQ130', 'BPQ020', 'BPQ050A', 'BPQ080',
       'BPQ100D', 'DIQ010', 'MCQ170M', 'SMQ681', 'PAQ610', 'PAD615', 'PAQ625',
       'PAD630', 'PAQ655', 'PAD660', 'PAQ670', 'PAD675', 'Systolic',
       'Diastolic'],
      dtype='object')

In [55]:
df.BPQ080.unique()

array([ 2.,  1., nan])

In [56]:
df.BPQ100D.unique()

array([ 2.,  1., nan,  9.])

In [57]:
df.loc[df.BPQ100D==9,'BPQ100D']=np.nan

In [58]:
df.DIQ010.unique()

array([ 2.,  1.,  3., nan])

In [59]:
df.MCQ170M.unique()

array([ 2.,  1., nan])

In [60]:
df.SMQ681.unique()

array([ 1.,  2., nan])

In [61]:
df.PAQ610.unique()

array([ 0.,  1.,  3.,  2.,  5.,  7.,  4.,  6., nan])

In [62]:
df.PAD615.describe()

count    4644.000000
mean       37.182386
std        99.961609
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       840.000000
Name: PAD615, dtype: float64

In [63]:
#checking for those with really small values
df[(df.PAD615>0)&(df.PAD615<0.01)].shape

(0, 45)

In [64]:
df.PAQ625.unique()

array([ 0.,  4.,  7.,  2.,  3.,  5.,  6.,  1., nan])

In [65]:
df.PAD630.describe()

count    4642.000000
mean       58.912107
std       115.500455
min         0.000000
25%         0.000000
50%         0.000000
75%        60.000000
max       990.000000
Name: PAD630, dtype: float64

In [66]:
#checking for those with really small values
df[(df.PAD630>0)&(df.PAD630<0.01)].shape

(0, 45)

In [67]:
df.PAQ655.unique()

array([ 0.,  2.,  6.,  5.,  3.,  1.,  4.,  7., nan])

In [68]:
df.PAD660.describe()

count    4654.000000
mean       17.461753
std        42.799350
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       480.000000
Name: PAD660, dtype: float64

In [69]:
#checking for those with really small values
df[(df.PAD660>0)&(df.PAD660<0.01)].shape

(0, 45)

In [70]:
df.PAQ670.unique()

array([ 0.,  4.,  5.,  2.,  7.,  1.,  3.,  6., nan])

In [71]:
df.PAD675.describe()

count    4652.000000
mean       25.812984
std        48.430493
min         0.000000
25%         0.000000
50%         0.000000
75%        30.000000
max       600.000000
Name: PAD675, dtype: float64

In [72]:
#checking for those with really small values
df[(df.PAD675>0)&(df.PAD675<0.01)].shape

(0, 45)

In [73]:
df.Systolic.describe()

count    4580.000000
mean      124.016157
std        18.258561
min        64.666667
25%       111.333333
50%       120.666667
75%       134.000000
max       228.666667
Name: Systolic, dtype: float64

In [74]:
df.Diastolic.describe()

count    4.580000e+03
mean     6.877052e+01
std      1.270026e+01
min      5.397605e-79
25%      6.200000e+01
50%      6.933333e+01
75%      7.600000e+01
max      1.280000e+02
Name: Diastolic, dtype: float64

Again there looks to be some error.  For those with very small diastolic readings, they will be dropped

In [75]:
df.Diastolic.sort_values()

2423    5.397605e-79
1951    5.397605e-79
4824    5.397605e-79
4408    5.397605e-79
2709    5.397605e-79
            ...     
4867             NaN
4875             NaN
4909             NaN
4920             NaN
4984             NaN
Name: Diastolic, Length: 4658, dtype: float64

In [76]:
df[df.Diastolic<1].index

Int64Index([ 674, 1353, 1361, 1402, 1793, 1951, 2423, 2709, 3741, 3856, 3868,
            4408, 4819, 4824],
           dtype='int64')

In [77]:
df.drop(df[df.Diastolic<1].index,axis=0,inplace=True)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4644 entries, 0 to 5002
Data columns (total 45 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   LBXTC      4644 non-null   float64
 1   RIAGENDR   4644 non-null   float64
 2   RIDRETH3   4644 non-null   float64
 3   RIDAGEYR   4644 non-null   float64
 4   BMXWT      4622 non-null   float64
 5   BMXHT      4619 non-null   float64
 6   BMXBMI     4614 non-null   float64
 7   BPXPLS     4567 non-null   float64
 8   BPXPULS    4568 non-null   float64
 9   DR1TKCAL   4644 non-null   float64
 10  DR1TPROT   4644 non-null   float64
 11  DR1TCARB   4644 non-null   float64
 12  DR1TSUGR   4644 non-null   float64
 13  DR1TFIBE   4644 non-null   float64
 14  DR1TTFAT   4644 non-null   float64
 15  DR1TSFAT   4644 non-null   float64
 16  DR1TMFAT   4644 non-null   float64
 17  DR1TPFAT   4644 non-null   float64
 18  DR1TCHOL   4644 non-null   float64
 19  DR1TSODI   4644 non-null   float64
 20  DR1TVD  

In [84]:
#writing the cleaned file so it can be used for modeling
df.to_csv('../Data/df_cleaned.csv')