In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [2]:
df = pd.read_csv('../Data/df_cleaned2.csv')
df.drop('Unnamed: 0',axis=1,inplace=True)
df.columns

Index(['LBXTC', 'RIAGENDR', 'RIDRETH3', 'RIDAGEYR', 'BMXWT', 'BMXHT', 'BMXBMI',
       'BPXPLS', 'BPXPULS', 'DR1TKCAL', 'DR1TPROT', 'DR1TCARB', 'DR1TSUGR',
       'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT', 'DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL',
       'DR1TSODI', 'DR1TVD', 'DR1TCALC', 'DR1TIRON', 'DR1TPOTA', 'DR1_300',
       'ALQ120Q', 'ALQ120U', 'ALQ130', 'BPQ020', 'BPQ050A', 'BPQ080',
       'BPQ100D', 'DIQ010', 'MCQ170M', 'SMQ681', 'PAQ610', 'PAD615', 'PAQ625',
       'PAD630', 'PAQ655', 'PAD660', 'PAQ670', 'PAD675', 'Systolic',
       'Diastolic', 'outlier'],
      dtype='object')

What I plan to do is impute missing values using KNNImputer.  I will create columns that denote wether or not the value was imputed.  Then I need to go through categorical variables and make sure the imputed values make sense.

In [3]:
imputer = KNNImputer()

In [4]:
imputed_values = imputer.fit_transform(df)

In [5]:
df2 = pd.DataFrame(imputed_values, columns=df.columns)
df2.head()

LBXTC  RIAGENDR  RIDRETH3  RIDAGEYR  BMXWT  BMXHT  BMXBMI  BPXPLS  BPXPULS  \
0  265.0       1.0       3.0      53.0   90.4  171.4    30.8    72.0      1.0   
1  229.0       1.0       3.0      78.0   83.4  170.1    28.8    56.0      1.0   
2  204.0       2.0       4.0      42.0   55.2  164.9    20.3    76.0      1.0   
3  190.0       2.0       1.0      72.0   64.4  150.0    28.6    64.0      1.0   
4  164.0       1.0       4.0      22.0   76.6  165.4    28.0    66.0      1.0   

   DR1TKCAL  ...  PAD615  PAQ625  PAD630  PAQ655  PAD660  PAQ670  PAD675  \
0    2964.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1    2482.0  ...     0.0     4.0   240.0     0.0     0.0     0.0     0.0   
2     604.0  ...     0.0     7.0   480.0     0.0     0.0     0.0     0.0   
3    1304.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4    2338.0  ...     0.0     0.0     0.0     2.0    60.0     0.0     0.0   

     Systolic  Diastolic  outlier  
0  140.000000  86.000000      0.0  
1  135.333333  45.333333      0.0  
2  104.000000  60.000000      0.0  
3  119.333333  58.666667      0.0  
4  111.333333  72.666667      0.0  

[5 rows x 46 columns]

In [6]:
df.head()

LBXTC  RIAGENDR  RIDRETH3  RIDAGEYR  BMXWT  BMXHT  BMXBMI  BPXPLS  BPXPULS  \
0  265.0       1.0       3.0      53.0   90.4  171.4    30.8    72.0      1.0   
1  229.0       1.0       3.0      78.0   83.4  170.1    28.8    56.0      1.0   
2  204.0       2.0       4.0      42.0   55.2  164.9    20.3    76.0      1.0   
3  190.0       2.0       1.0      72.0   64.4  150.0    28.6    64.0      1.0   
4  164.0       1.0       4.0      22.0   76.6  165.4    28.0    66.0      1.0   

   DR1TKCAL  ...  PAD615  PAQ625  PAD630  PAQ655  PAD660  PAQ670  PAD675  \
0    2964.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1    2482.0  ...     0.0     4.0   240.0     0.0     0.0     0.0     0.0   
2     604.0  ...     0.0     7.0   480.0     0.0     0.0     0.0     0.0   
3    1304.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4    2338.0  ...     0.0     0.0     0.0     2.0    60.0     0.0     0.0   

     Systolic  Diastolic  outlier  
0  140.000000  86.000000        0  
1  135.333333  45.333333        0  
2  104.000000  60.000000        0  
3  119.333333  58.666667        0  
4  111.333333  72.666667        0  

[5 rows x 46 columns]

In [7]:
for column in df.columns:
    if (df[column].isna().sum()>0):
        df2["{}_i".format(column)]=1*df[column].isna()


In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4644 entries, 0 to 4643
Data columns (total 72 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   LBXTC        4644 non-null   float64
 1   RIAGENDR     4644 non-null   float64
 2   RIDRETH3     4644 non-null   float64
 3   RIDAGEYR     4644 non-null   float64
 4   BMXWT        4644 non-null   float64
 5   BMXHT        4644 non-null   float64
 6   BMXBMI       4644 non-null   float64
 7   BPXPLS       4644 non-null   float64
 8   BPXPULS      4644 non-null   float64
 9   DR1TKCAL     4644 non-null   float64
 10  DR1TPROT     4644 non-null   float64
 11  DR1TCARB     4644 non-null   float64
 12  DR1TSUGR     4644 non-null   float64
 13  DR1TFIBE     4644 non-null   float64
 14  DR1TTFAT     4644 non-null   float64
 15  DR1TSFAT     4644 non-null   float64
 16  DR1TMFAT     4644 non-null   float64
 17  DR1TPFAT     4644 non-null   float64
 18  DR1TCHOL     4644 non-null   float64
 19  DR1TSO

Now I need to go through the categorical values and make sure the values make sense

In [10]:
df2.BPXPULS.unique()

array([1. , 2. , 1.2])

In [11]:
df2.loc[df2.BPXPULS==1.2,'BPXPULS']=1

In [12]:
df2.BPXPULS.unique()

array([1., 2.])

In [13]:
df2.DR1_300.unique()

array([2. , 1. , 3. , 2.4, 2.2, 2.8, 1.8])

In [14]:
df2.loc[df2.DR1_300==1.8,'DR1_300']=2
df2.loc[df2.DR1_300==2.2,'DR1_300']=2
df2.loc[df2.DR1_300==2.4,'DR1_300']=2
df2.loc[df2.DR1_300==2.8,'DR1_300']=3
df2.DR1_300.unique()

array([2., 1., 3.])

In [15]:
df2.ALQ120U.unique()

array([1. , 2.2, 3. , 2. , 1.6, 1.8, 1.4, 2.4, 1.2, 2.6, 2.8])

In [16]:
df2.loc[df2.ALQ120U==2.2,'ALQ120U']=2
df2.loc[df2.ALQ120U==1.6,'ALQ120U']=2
df2.loc[df2.ALQ120U==1.8,'ALQ120U']=2
df2.loc[df2.ALQ120U==1.4,'ALQ120U']=1
df2.loc[df2.ALQ120U==2.4,'ALQ120U']=2
df2.loc[df2.ALQ120U==1.2,'ALQ120U']=1
df2.loc[df2.ALQ120U==2.6,'ALQ120U']=3
df2.loc[df2.ALQ120U==2.8,'ALQ120U']=3
df2.ALQ120U.unique()

array([1., 2., 3.])

In [17]:
df2.BPQ020.unique()

array([2. , 1. , 1.6, 1.2, 1.4, 1.8])

In [18]:
df2.loc[df2.BPQ020==1.6,'BPQ020']=2
df2.loc[df2.BPQ020==1.2,'BPQ020']=1
df2.loc[df2.BPQ020==1.4,'BPQ020']=1
df2.loc[df2.BPQ020==1.8,'BPQ020']=2
df2.BPQ020.unique()



array([2., 1.])

In [20]:
df2.BPQ050A.unique()

array([2. , 1. , 1.6, 1.2, 1.8])

In [21]:
df2.loc[df2.BPQ050A==1.6,'BPQ050A']=2
df2.loc[df2.BPQ050A==1.2,'BPQ050A']=1
df2.loc[df2.BPQ050A==1.8,'BPQ050A']=2
df2.BPQ050A.unique()


array([2., 1.])

In [22]:
df2.BPQ080.unique()

array([2. , 1. , 1.6, 1.4, 1.8, 1.2])

In [24]:
df2['BPQ080'] = df2.BPQ080.round()

In [27]:
df2['BPQ100D']=df2.BPQ100D.round()

In [29]:
df2['DIQ010']=df2.DIQ010.round()

In [31]:
df2['MCQ170M']=df2.MCQ170M.round()

In [33]:
df2['SMQ681']=df2.SMQ681.round()

In [34]:
df2['PAQ610']=df2.PAQ610.round()

In [35]:
df2['PAQ625']=df2.PAQ625.round()

In [36]:
df2['PAQ655']=df2.PAQ655.round()

In [37]:
df2['PAQ670']=df2.PAQ670.round()

In [38]:
df2.to_csv('../Data/imputed.csv')